apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3

  bootstrap:
    initdb:
      database: bookstore
      owner: bookdbadmin
      secret:
        name: postgresql-app-user
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: db-init-script
            key: init.sql

  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-superuser

  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: gp3
    size: 2Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
