apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
stringData:
  DOCKER_DATABASE_URL: "postgresql://bookdbadmin:dbpassword@db:5432/bookstore"
  POSTGRES_MASTER: "postgres"
  POSTGRES_MASTER_PASSWORD: "postgres"
  WORKSHOP_POSTGRES_USER: "bookdbadmin"
  WORKSHOP_POSTGRES_PASSWORD: "dbpassword"
  WORKSHOP_POSTGRES_DB: "bookstore"
