apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
stringData:
  DOCKER_DATABASE_URL: "postgresql://bookdbadmin:dbpassword@postgresql-rw:5432/bookstore"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-app-user
type: kubernetes.io/basic-auth
stringData:
  username: bookdbadmin
  password: dbpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-superuser
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres
