apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../modules/kgateway
  - kgateway-gatewayclass.yaml
  - kgateway-gateway.yaml
  - kgateway-gloo-gateway.yaml
  - sample-app-vs.yaml
  - kgateway-alb.yaml
