apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-observability-namespace.yaml
  - cert-manager-namespace.yaml
  - cnpg-system-namespace.yaml
  - fargate-namespace.yaml
  - garage-namespace.yaml
  - kgateway-namespace.yaml
  - nats-namespace.yaml
  - sample-app-namespace.yaml
