apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../modules/aws-csi
  - ../../modules/aws-logging
  - ../../modules/aws-load-balancer-controller
  - ../../modules/cluster-autoscaler
  - ../../modules/cloudnative-pg
  - ../../modules/sample-app
  - cert-manager
  - cluster-information-configmap.yaml
  - kgateway
